apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-logger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-logger
  template:
    metadata:
      labels:
        app: dotnet-logger
    spec:
      containers:
        - name: dotnet-logger
          image: karenchibukhchyandevops/k8sproject:latest
          volumeMounts:
            - name: log-volume
              mountPath: /app/Logs
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/logs
            type: DirectoryOrCreate