apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJrYXJlbmNoaWJ1a2hjaHlhbmRldm9wcyIsInBhc3N3b3JkIjoiZGNrcl9wYXRfcV9TSDR5VS03N3p6bG9ObjNfLUE4cWFZajkwIiwiYXV0aCI6ImEyRnlaVzVqYUdsaWRXdG9ZMmg1WVc1a1pYWnZjSE02WkdOcmNsOXdZWFJmY1Y5VFNEUjVWUzAzTjNwNmJHOU9iak5mTFVFNGNXRlphamt3In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
